language: python

python:
  - '3.8'

addons:
  firefox: latest

branches:
  only:
    - staging
    - master
    
install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - install-webdrivers --path webdrivers

env:
  global:
    - DJANGO_SETTINGS_MODULE="nutella_platform.settings.travis"

services:
  - postgresql

script:
  - python manage.py test -v