language: python
python:
  - '3.5'

# safelist
branches:
  only:
    - staging
    - master

before_script:
  - pip3 install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=nutella_platform.settings.travis

script:
  - python manage.py test