language: python
python:
  - '3.6'

# safelist
branches:
  only:
    - staging
    - master

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=nutella_platform.settings.travis

script:
  - python manage.py test