dist: bionic
language: python

python:
  - '3.8'

branches:
  only:
    - staging
    - master

addons:
  firefox: latest

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.29.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
    
install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - install-webdrivers --path webdrivers

env:
  global:
    - DJANGO_SETTINGS_MODULE="nutella_platform.settings.travis"

services:
  - postgresql

script:
  - python manage.py runserver
  - python manage.py test
