# Generated by Django 3.1.4 on 2020-12-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password_hash', models.CharField(max_length=256, unique=True)),
                ('nom', models.CharField(max_length=45, null=True)),
                ('prenom', models.CharField(max_length=45, null=True)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('phone', models.CharField(max_length=14, null=True, unique=True)),
                ('date_birth', models.DateTimeField(null=True)),
                ('date_created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField()),
            ],
        ),
    ]
