# Generated by Django 3.1.4 on 2020-12-16 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purbeurre', '0002_auto_20201216_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.ManyToManyField(related_name='save_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
