# Generated by Django 3.1.4 on 2020-12-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0003_auto_20201210_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_pur_beurre',
            name='inputSex',
        ),
    ]
