# Generated by Django 3.1.4 on 2020-12-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0003_auto_20201216_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='save_product',
        ),
    ]
