# Generated by Django 3.1.4 on 2020-12-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0005_auto_20201216_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='countries',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_openfoodfacts',
            field=models.CharField(max_length=800, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
