# Generated by Django 3.1.4 on 2021-01-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0007_product_nutriments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['-id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
