# Generated by Django 3.1.4 on 2020-12-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0004_auto_20201216_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='countries',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(max_length=800, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=800, unique=True),
        ),
    ]
