# Generated by Django 3.1.4 on 2020-12-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0006_auto_20201216_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutriments',
            field=models.CharField(default=0, max_length=8000),
            preserve_default=False,
        ),
    ]
