# Generated by Django 3.1.4 on 2021-02-08 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purbeurre', '0009_product_like_disklike_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like_disklike_products',
        ),
        migrations.AddField(
            model_name='product',
            name='disklike_products',
            field=models.ManyToManyField(related_name='disklike_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='like_products',
            field=models.ManyToManyField(related_name='like_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
